### ISSUE TITLE
scrollToEnd is not a function when i use custom SendTextBox

### ISSUE THREAD

**Issue by ShtirlicC4** [microsoft/BotFramework-WebChat#3549]
When i use a custom TextBox created with connectSendTextBox on onKeyPress Enter, an error "scrollToEnd is not a function" appears.

```jsx
export default connectSendTextBox()((connect) => {
  return (
    <input 
      onChange={connect.onChange} 
      onKeyPress={connect.onKeyPress}
      type="text" />
  )
});
```

**Comment by v-kydela** [comment]
Thank you for the report, @ShtirlicC4 

I'm not sure I'll be able to reproduce the problem using only the information you've provided. Can you link to any samples or documentation you've followed?

**Comment by ShtirlicC4** [comment]
Hi.
i used "botframework-webchat": "^4.5.1" after updated to 4.10 version i get this error. 

I write message in my custom textBox component and press Enter, after that in console an error with this text appears 

scrollToEnd is not a function at onKeyPress (TextBox.js:266) and etc.

Sorry but i can`t find tutorial anymore, before with botframework-webchat: "4.5.1" i used that method [connectSendTextBox](https://github.com/microsoft/BotFramework-WebChat/blob/d1c776b29e72d52f76eed64d1a160f8aa6603e8e/packages/component/src/SendBox/TextBox.js#L31)

my code looks something like that:

```
import ReactWebChat, { Components, createBrowserWebSpeechPonyfillFactory } from 'botframework-webchat';
const { Composer, SuggestedActions } = Components;
const webChatCreateDirectLine = (options) => {
  webChatDirectLine = createDirectLine({
    ...options,
    webSpeechPonyfillFactory: createBrowserWebSpeechPonyfillFactory()
  });
};
const CustomSendBox connectSendTextBox()((connect: any) => {
  const value = connect.store.getState().sendBoxValue;
  const onFocus = () => widgetStore.dispatch(abortProactivity());
  return (
    <input 
      value={value} 
      onChange={connect.onChange} 
      onKeyPress={connect.onKeyPress}
      type="text" />
	);
});
class WebChat extends React.Component {
	render() {
		return (
		    <ReactWebChat
				directLine={webChatDirectLine}
				locale="en-US"
			/>
			<Composer
              directLine={webChatDirectLine}
              locale="en-US"
			>
				<CustomSendBox />
            </Composer>);
		}
	}

}
```

**Comment by v-kydela** [comment]
@ShtirlicC4 - Your code doesn't seem to be valid JSX. Is that the actual code you're trying to run or did you perhaps not copy and paste it correctly?

**Comment by v-kydela** [comment]
@ShtirlicC4 - Are you still working on this?

**Comment by v-kydela** [comment]
I am closing this issue due to inactivity. We are still happy to provide help if you need any, though it may be a good idea to make a new post if that's the case. Please have a look at [this](https://github.com/microsoft/botframework-sdk#questions-and-help) to find out the best places to ask for help, and consider asking questions on Stack Overflow.
