### ISSUE TITLE
Web Chat turn blank when sending the first message

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3046]
## Version

`4.8.0` installed thru NPM. It does not affect `webchat.js` hosted from cdn.botframework.com.

## Describe the bug

`globalize@1.5.0` recently introduced a bug that cause JavaScript error on formatting a date. The bug was not on `globalize@1.4.2` (used by `webchat.js`) and `@1.4.3` (last known good).

## Steps to reproduce

1. `npx create-react-app app`
1. `cd app`
1. `npm install botframework-webchat`
1. Instantiate Web Chat control in the React app
1. Send a message

## Expected behavior

The message should send successfully.

## Workarounds

Before `globalize` fixed the bug, there are 2 workarounds:

### Install `globalize@1.4.2` locally

Before installing Web Chat, run `npm install globalize@1.4.2`. This will install a local version of `globalize`. Since Web Chat depends on `@^1.4.2`, NPM should use this local version (`@1.4.2) instead of most updated version on NPM (`@1.5.0`).

You can verify by:

- `cat node_modules/globalize/package.json`
   - `version` should read `1.4.2`
- `ls node_modules/botframework-webchat/node_modules`
   - There should be no `globalize` installed under `botframework-webchat`

### Modify `package-lock.json`

Modify `package-lock.json` to use `globalize@1.4.2`.

```json
    "globalize": {
      "version": "1.4.2",
      "resolved": "https://registry.npmjs.org/globalize/-/globalize-1.4.2.tgz",
      "integrity": "sha512-IfKeYI5mAITBmT5EnH8kSQB5uGson4Fkj2XtTpyEbIS7IHNfLHoeTyLJ6tfjiKC6cJXng3IhVurDk5C7ORqFhQ==",
      "requires": {
        "cldrjs": "^0.5.0"
      }
    },
```

[Bug]

**Comment by arnab-chatterjee-jdas** [comment]
Any fix for this bug yet?

**Comment by corinagum** [comment]
No change. globalizejs has not yet responded to the bug filed on their repo. Please track https://github.com/globalizejs/globalize/issues/895 for updates.

**Comment by arnab-chatterjee-jdas** [comment]
Thanks for the workaround @compulim

**Comment by kmkaliraj** [comment]
I am also stuck with the same issue? May know when the fix will be ready?

**Comment by bencrabtree** [comment]
I am not using globalize but am getting the same error since upgrading to 4.8.0. The error traces back to our custom middleware for webchat's store. Our intended behavior is to use the avatar middleware to render custom avatars for multiple users. Full error is documented below:

`number.js:579 Uncaught TypeError: numberToPartsFormatter is not a function
    at Object.numberFormatter (number.js:579)
    at date.js:697
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at dateFormat (date.js:388)
    at dateToPartsFormatter (date.js:1575)
    at dateFormatter (date.js:715)
    at useDateFormatter.js:31
    at StackedLayout (StackedLayout.js:167)
    at renderWithHooks (react-dom.development.js:16260)
react-dom.development.js:21843 The above error occurred in the <StackedLayout> component:
    in StackedLayout (created by BasicTranscript)
    in li (created by BasicTranscript)
    in ul (created by BasicTranscript)
    in div (created by Panel)
    in Panel (created by Context.Consumer)
    in _default (created by BasicTranscript)
    in div (created by BasicTranscript)
    in BasicTranscript (created by Composer)
    in div (created by FocusBox)
    in FocusBox (created by Composer)
    in Composer (created by Composer)
    in Composer (created by Context.Consumer)
    in Composer (created by ComposeWithStore)
    in Provider (created by ComposeWithStore)
    in ErrorBoundary (created by ComposeWithStore)
    in ComposeWithStore (created by BasicWebChat)
    in BasicWebChat (created by FullReactWebChat)
    in AdaptiveCardsComposer (created by FullReactWebChat)
    in FullReactWebChat (created by Chat)`

**Comment by jriley15** [comment]
@compulim Is this fixed now in 4.9.2?
