### ISSUE TITLE
WebChat v0.11.0 fails build with DirectLine 0.9.10

### ISSUE THREAD

**Issue by telkomops** [Microsoft/BotFramework-WebChat#599]
WebChat v0.11.0 fails build with directline 0.9.10
src/Attachment.tsx(163,29): error TS2339: Property 'content' does not exist on t
ype 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(166,28): error TS2339: Property 'content' does not exist on t
ype 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(167,28): error TS2339: Property 'content' does not exist on t
ype 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(167,51): error TS7006: Parameter 'img' implicitly has an 'any
' type.
src/Attachment.tsx(169,50): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(171,191): error TS2339: Property 'content' does not exist on
type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(175,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(178,28): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(178,57): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(180,62): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(181,62): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(182,58): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(183,62): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(184,60): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(186,59): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(189,201): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(193,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(193,52): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(193,80): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(196,104): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(199,42): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(201,45): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(201,73): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(202,47): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(203,43): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(210,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(210,52): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(210,80): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(213,108): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(215,53): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(216,42): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(218,45): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(218,73): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(219,47): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(220,43): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(226,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(226,52): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(226,80): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(229,104): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(232,42): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(233,47): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(234,43): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(240,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(243,105): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(247,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(250,56): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(252,24): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(252,52): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(252,71): error TS7006: Parameter 'fact' implicitly has an 'any' type.
src/Attachment.tsx(252,77): error TS7006: Parameter 'i' implicitly has an 'any' type.
src/Attachment.tsx(256,24): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(256,52): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(256,71): error TS7006: Parameter 'item' implicitly has an 'any' type.
src/Attachment.tsx(256,77): error TS7006: Parameter 'i' implicitly has an 'any'type.
src/Attachment.tsx(272,56): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(275,56): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(276,54): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(278,163): error TS2339: Property 'content' does not exist ontype 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(282,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(285,58): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(290,29): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(293,103): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(294,48): error TS2339: Property 'content' does not exist on type 'Attachment'.
  Property 'content' does not exist on type 'Media'.
src/Attachment.tsx(302,44): error TS2339: Property 'contentUrl' does not exist on type 'Attachment'.
  Property 'contentUrl' does not exist on type 'HeroCard'.
src/Attachment.tsx(306,57): error TS2339: Property 'contentUrl' does not exist on type 'Attachment'.
  Property 'contentUrl' does not exist on type 'HeroCard'.
src/Attachment.tsx(309,60): error TS2339: Property 'thumbnailUrl' does not exist on type 'Attachment'.
  Property 'thumbnailUrl' does not exist on type 'HeroCard'.
src/Attachment.tsx(309,92): error TS2339: Property 'contentUrl' does not exist on type 'Attachment'.
  Property 'contentUrl' does not exist on type 'HeroCard'.

**Comment by junqi** [comment]
I encountered same fails.

FYI:
I could suppress error messages as temporary solution by below changes to Attachment.tsx
1. change [here](https://github.com/Microsoft/BotFramework-WebChat/blob/e573a740a3b7f5a19ef615b3dfae8b6c24f967ed/src/Attachment.tsx#L3) to `import { Attachment, CardAction, KnownMedia } from 'botframework-directlinejs';`
2. change [here](https://github.com/Microsoft/BotFramework-WebChat/blob/e573a740a3b7f5a19ef615b3dfae8b6c24f967ed/src/Attachment.tsx#L147) to `const attachment = props.attachment as KnownMedia;`

**Comment by telkomops** [comment]
Thanks @junqi , i wanted to point out that, this version was using 0.9.10, the tag is not available on directline github repo. Looks like 0.9.10 , is being upgraded at the same time for speech and next version.

**Comment by danmarshall** [comment]
Hi @telkomops can you delete the directlinejs from your node_modules folder and re-install ?

**Comment by telkomops** [comment]
Worked with 0.9.8
