### ISSUE TITLE
install fails with typescript error

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotFramework-WebChat#445]
Cloned the repo. Ran `npm install`. Got below error.

```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> botframework-webchat@0.10.6 prepublish /Users/bhushanvadgave/org/test/BotFramework-WebChat
> tsc && npm run build-css && webpack --progress --config webpack.production.config.js

src/ActivityView.tsx(29,21): error TS2322: Type '{ format: FormatState; size: SizeState; onCardAction: IDoCardAction; onImageLoad: () => void; key...' is not assignable to type 'IntrinsicAttributes & { format: FormatState; attachment: Attachment; onCardAction: IDoCardAction;...'.
  Property 'size' does not exist on type 'IntrinsicAttributes & { format: FormatState; attachment: Attachment; onCardAction: IDoCardAction;...'.
src/ActivityView.tsx(73,29): error TS2322: Type '{ children?: ReactNode; format: FormatState; size: SizeState; onCardAction: IDoCardAction; onImag...' is not assignable to type 'IntrinsicAttributes & { attachments: Attachment[]; attachmentLayout: AttachmentLayout; format: Fo...'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { attachments: Attachment[]; attachmentLayout: AttachmentLayout; format: Fo...'.
src/Attachment.tsx(86,17): error TS2322: Type '{ src: string; poster?: string; autoPlay?: boolean; loop?: boolean; onLoad?: () => void; onClick?...' is not assignable to type 'IntrinsicAttributes & { embedId: string; autoPlay?: boolean; loop?: boolean; }'.
  Property 'src' does not exist on type 'IntrinsicAttributes & { embedId: string; autoPlay?: boolean; loop?: boolean; }'.
src/Attachment.tsx(92,27): error TS2322: Type '{ src: string; poster?: string; autoPlay?: boolean; loop?: boolean; onLoad?: () => void; onClick?...' is not assignable to type 'IntrinsicAttributes & { embedId: string; autoPlay?: boolean; loop?: boolean; }'.
  Property 'src' does not exist on type 'IntrinsicAttributes & { embedId: string; autoPlay?: boolean; loop?: boolean; }'.
src/Attachment.tsx(110,27): error TS2322: Type '{ src: string; type?: "audio" | "video" | "image"; poster?: string; autoPlay?: boolean; loop?: bo...' is not assignable to type 'IntrinsicAttributes & { src: string; poster?: string; autoPlay?: boolean; loop?: boolean; onLoad?...'.
  Property 'type' does not exist on type 'IntrinsicAttributes & { src: string; poster?: string; autoPlay?: boolean; loop?: boolean; onLoad?...'.
src/Carousel.tsx(56,42): error TS2322: Type '{ children?: ReactNode; format: FormatState; size: SizeState; attachments: Attachment[]; onCardAc...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<CarouselAttachments> & Readonly<{ children?: React...'.
  Property 'size' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<CarouselAttachments> & Readonly<{ children?: React...'.
src/Carousel.tsx(77,37): error TS2322: Type '{ children?: ReactNode; format: FormatState; onCardAction: IDoCardAction; onImageLoad: () => void...' is not assignable to type 'IntrinsicAttributes & { format: FormatState; attachment: Attachment; onCardAction: IDoCardAction;...'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { format: FormatState; attachment: Attachment; onCardAction: IDoCardAction;...'.

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! botframework-webchat@0.10.6 prepublish: `tsc && npm run build-css && webpack --progress --config webpack.production.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the botframework-webchat@0.10.6 prepublish script 'tsc && npm run build-css && webpack --progress --config webpack.production.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the botframework-webchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && npm run build-css && webpack --progress --config webpack.production.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs botframework-webchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls botframework-webchat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bhushanvadgave/.npm/_logs/2017-05-04T07_42_56_767Z-debug.log
```
Using nodejs 6.10 and npm 4.2.

**Comment by billba** [comment]
Works fine on OS X using npm version 3.10.9 - sounds like npm 4.2 is causing problems. Adjusted title accordingly.

**Comment by bhushanvadgave** [comment]
Even with npm 3.10.9 I'm facing the same issue. Don't know if the root cause of the problem is only in my system but I tried reinstalling the nodejs as well.

**Comment by bhushanvadgave** [comment]
@billba Can you try removing the node_modules, cleaning the npm cache and then running "npm install"? I guess new release of some dependency might be causing this issue.

**Comment by billba** [comment]
We are indeed experiencing build issues due to new TypeScript and some other dependencies. We will clear them out in the near future.

**Comment by wsb252** [comment]
same issue on npm 4.5

**Comment by billba** [comment]
Problems are generic. Updated title accordingly.

**Comment by wsb252** [comment]
FYI - Found a workaround.  Updated package.json to explicitly use typescript 2.2.2 and everything builds successfully.

Change:
"typescript": "^2.2.2"

To be:
"typescript": "2.2.2"

**Comment by bhushanvadgave** [comment]
Yes it solved. Thank you @wsb252

**Comment by TomHulme** [comment]
I tried all of the above but still had the issue. Even upgraded from VS2015 to VS2017 and nothing changed. BUT deleting this folder seemed to fix it on my machine.
`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\{VERSION_NUMBER}\TypeScript `

**Comment by 82antu** [comment]
Same Issue Here;

2.2.2 Version seems work.
